### ISSUE TITLE
Replaces default Lua Package

### ISSUE THREAD

**Issue by qazokm** [bhargavrpatel/Dota-2-Sublime-Packages#1]
Great package, except it cannot be removed/disabled when trying to open a normal Lua file.

**Comment by bhargavrpatel** [comment]
I will recreate this set of snippets as a package instead. Will need some time though. 
The reason for that is because it detects for lua files.

**Comment by qazokm** [comment]
Ye, I assumed that, I tried to mess around with the detection but I have very little knowledge of Sublime packages.
