### ISSUE TITLE
We need Dota-2-Sublime-Packages for atom.io

### ISSUE THREAD

**Issue by WaKeMaTTa** [bhargavrpatel/Dota-2-Sublime-Packages#2]
We need Dota-2-Sublime-Packages for [atom.io](http://atom.io)

**Comment by bhargavrpatel** [comment]
Indeed. I use atom for my current projects. I will see what I can do.

**Comment by WaKeMaTTa** [comment]
:+1:

**Comment by Faultless** [comment]
https://github.com/Faultless/language-dotakv
Made this package. I'm a total newb to the world of modding / packaging so I'll need help to fix all the issues and turn it into a decent usable package.

**Comment by WaKeMaTTa** [comment]
I will stay stuned in your package.

**Comment by Faultless** [comment]
I've made a package and it's at least working: https://atom.io/packages/language-dotakv
I'll be fixing indentation issues and maybe create another package for Dota Lua support. 
But I'll wait for @bhargavrpatel 's approval before doing something potentially illegal or disrespectful for his work.

**Comment by WaKeMaTTa** [comment]
:+1:

**Comment by bhargavrpatel** [comment]
By all means. Please use whatever you need from here to get the Atom packages working. I no longer take part in this project. For all intensive purposes, the owner of this project is MNoya. 

I am on my phone but when I am home, I will checkout the repo and link it here for those wanting a solution for Atom. 

I also suggest you link your project on the official wiki as well as the community forums.

Best of luck,
Regards.

**Comment by Faultless** [comment]
Sorry for rebumping this but here's the Lua snippets package I tried to reproduce: 
https://atom.io/packages/language-dotalua
