### ISSUE TITLE
Is the creator still around? Open to updating?

### ISSUE THREAD

**Issue by darklordabc** [bhargavrpatel/Dota-2-Sublime-Packages#3]
As the title says, a lot of modders still use this package, if somebody made improvements, would the creator of this package be around to merge it?

**Comment by kirugan** [comment]
Why are you asking?

**Comment by natanfudge** [comment]
The white book has eaten him

**Comment by bhargavrpatel** [comment]
@darklordabc @natanfudge I have yet to see any Pull request which I could consider merging in. If there are any improvements you two have in mind, feel free to create a pull request.

I will go ahead and add Contributing section in the README to avoid any confusion.
